#!/usr/bin/env python3
"""
Amap (Gaode) Batch Injection Script Generator
===============================================
Converts GCJ-02 coordinates to Amap's internal Web Mercator pixel coordinates
(zoom level 20), then generates a JavaScript file that can be pasted into the
Chrome Console on amap.com to batch-add all favorites via the addFav API.

Why this works:
  - Amap's addFav API uses Web Mercator pixel coordinates, not decimal degrees
  - The API requires an x-csrf-token from the browser's Cookie
  - Running JS in the user's own browser bypasses Amap's anti-bot verification
  - 2.5s delay between requests prevents rate limiting

Usage:
    python3 generate_amap_js.py [--input baidu_favorites_gcj02.json] [--output amap_batch_add.js] [--delay 2.5]

Then:
    1. Open amap.com in Chrome and log in
    2. F12 → Console
    3. Paste the entire amap_batch_add.js content
    4. Type batchAddFavorites() and press Enter
    5. Wait ~20 minutes for completion (487 items × 2.5s)
"""

import json
import math
import os
import sys
import hashlib
import argparse


def lnglat_to_amap_pixel(lng, lat):
    """
    Convert GCJ-02 decimal degrees to Amap's internal Web Mercator
    pixel coordinates at zoom level 20.

    Total pixels at zoom 20 = 2^20 × 256 = 268,435,456

    Args:
        lng: GCJ-02 longitude (decimal degrees)
        lat: GCJ-02 latitude (decimal degrees)

    Returns:
        (point_x, point_y): integer pixel coordinates for Amap addFav API
    """
    TILE_SIZE = 256
    ZOOM = 20
    total_pixels = (2 ** ZOOM) * TILE_SIZE

    # Longitude: linear mapping
    x = (lng + 180.0) / 360.0 * total_pixels

    # Latitude: Mercator projection
    lat_rad = lat * math.pi / 180.0
    mercator = math.log(math.tan(math.pi / 4.0 + lat_rad / 2.0))
    y = (1.0 - mercator / math.pi) / 2.0 * total_pixels

    return int(round(x)), int(round(y))


def guess_city_code(name, address):
    """
    Determine city code from name/address text.
    Covers common Chinese cities. Add more as needed.
    """
    combined = (address or "") + " " + (name or "")
    cities = [
        ("北京", 110000), ("上海", 310000), ("广州", 440100),
        ("深圳", 440300), ("杭州", 330100), ("成都", 510100),
        ("武汉", 420100), ("南京", 320100), ("天津", 120000),
        ("重庆", 500000), ("西安", 610100), ("长沙", 430100),
        ("苏州", 320500), ("郑州", 410100), ("青岛", 370200),
        ("大连", 210200), ("厦门", 350200), ("宁波", 330200),
    ]
    for name, code in cities:
        if name in combined:
            return code, name
    return 110000, "北京"  # fallback


def generate_js(input_path, output_path, delay=2.5):
    """Generate the batch injection JavaScript file."""
    with open(input_path, encoding="utf-8") as f:
        data = json.load(f)

    items = []
    for i, fav in enumerate(data):
        px, py = lnglat_to_amap_pixel(fav["gcj02_lng"], fav["gcj02_lat"])
        city_code, city_name = guess_city_code(fav.get("name", ""), fav.get("address", ""))
        id_str = hashlib.md5(f'{fav["name"]}_{px}_{py}_{i}'.encode()).hexdigest()

        item = {
            "id": id_str,
            "data": {
                "item_id": id_str,
                "custom_name": fav["name"],
                "custom_address": fav.get("address", fav["name"]),
                "name": fav["name"],
                "address": fav.get("address", fav["name"]),
                "point_x": px,
                "point_y": py,
                "city_code": city_code,
                "city_name": city_name,
                "phone_numbers": "",
                "custom_phone_numbers": "",
                "comment": "",
                "tag": "",
                "top_time": "",
                "type": 1,  # 1 = custom/non-POI location
            },
            "type": 101,
            "ver": "alGtGQAAAAABAAAB",
        }
        items.append(item)

    json_data = json.dumps(items, ensure_ascii=False, separators=(",", ":"))

    js_code = f"""// ─── Amap Batch Add Favorites ──────────────────────────────────────────
// Generated by baidu-to-amap-migration tool
// {len(items)} items, {delay}s delay per item, ~{int(len(items) * delay / 60)} minutes total
//
// HOW TO USE:
//   1. Open https://www.amap.com/ in Chrome and log in
//   2. Open DevTools Console (F12 → Console)
//   3. Paste this ENTIRE file content and press Enter
//   4. Type: batchAddFavorites()
//   5. Wait until the alert popup appears
//
// WARNING: Do NOT close this tab or refresh while the script is running.

const FAVORITES = {json_data};
const TOTAL = FAVORITES.length;

async function addFavorite(item, index) {{
    const csrf = document.cookie.match(/x-csrf-token=([^;]+)/)?.[1] || '';
    const body = new URLSearchParams();
    body.append('data[0][id]', item.id);
    body.append('data[0][data][item_id]', item.data.item_id);
    body.append('data[0][data][custom_address]', item.data.custom_address);
    body.append('data[0][data][custom_name]', item.data.custom_name);
    body.append('data[0][data][type]', String(item.data.type));
    body.append('data[0][data][address]', item.data.address);
    body.append('data[0][data][phone_numbers]', '');
    body.append('data[0][data][comment]', '');
    body.append('data[0][data][name]', item.data.name);
    body.append('data[0][data][point_x]', String(item.data.point_x));
    body.append('data[0][data][point_y]', String(item.data.point_y));
    body.append('data[0][data][top_time]', '');
    body.append('data[0][data][city_code]', String(item.data.city_code));
    body.append('data[0][data][custom_phone_numbers]', '');
    body.append('data[0][data][city_name]', item.data.city_name);
    body.append('data[0][data][tag]', '');
    body.append('data[0][type]', '101');
    body.append('data[0][ver]', item.ver);

    const resp = await fetch('https://www.amap.com/service/fav/addFav', {{
        method: 'POST',
        headers: {{
            'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
            'x-csrf-token': csrf,
            'x-requested-with': 'XMLHttpRequest',
        }},
        body: body.toString(),
        credentials: 'include',
    }});
    const result = await resp.json();
    return result;
}}

async function batchAddFavorites() {{
    console.log('Starting batch: ' + TOTAL + ' favorites, ' + {delay} + 's delay each...');
    const DELAY = {int(delay * 1000)};
    let success = 0, failed = 0;
    const startTime = Date.now();

    for (let i = 0; i < TOTAL; i++) {{
        const pct = ((i + 1) / TOTAL * 100).toFixed(1);
        try {{
            const r = await addFavorite(FAVORITES[i], i);
            if (r && (r.code === 0 || r.data || r.message === 'success')) {{
                success++;
                console.log('[' + (i+1) + '/' + TOTAL + '] ' + pct + '% OK: ' + FAVORITES[i].data.name);
            }} else {{
                failed++;
                console.warn('[' + (i+1) + '/' + TOTAL + '] ' + pct + '% FAIL: ' + FAVORITES[i].data.name, r);
            }}
        }} catch(e) {{
            failed++;
            console.error('[' + (i+1) + '/' + TOTAL + '] ' + pct + '% ERROR: ' + FAVORITES[i].data.name, e.message);
        }}

        if (i < TOTAL - 1) {{
            await new Promise(r => setTimeout(r, DELAY));
        }}
    }}

    const elapsed = ((Date.now() - startTime) / 1000 / 60).toFixed(1);
    console.log('=== DONE === (elapsed: ' + elapsed + ' min)');
    console.log('Success: ' + success + ', Failed: ' + failed + ', Total: ' + TOTAL);
    alert('导入完成！已耗时: ' + elapsed + ' 分钟\\n' +
          '成功: ' + success + '\\n' +
          '失败: ' + failed + '\\n' +
          '总计: ' + TOTAL + '\\n\\n' +
          '刷新收藏页面查看结果 (F5)');
}}

console.log('Data loaded: ' + TOTAL + ' items. Type batchAddFavorites() to start.');
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(js_code)

    file_size = os.path.getsize(output_path)
    est_minutes = len(items) * delay / 60
    print(f"[DONE] Generated Amap injection script")
    print(f"       Output:  {os.path.abspath(output_path)} ({file_size} bytes)")
    print(f"       Items:   {len(items)}")
    print(f"       Delay:   {delay}s per item")
    print(f"       Est:     ~{est_minutes:.0f} minutes total")
    print()
    print("[NEXT STEPS]")
    print("  1. Open https://www.amap.com/ in your real Chrome and log in")
    print("  2. F12 → Console")
    print(f"  3. Paste ALL content of {output_path}")
    print("  4. Run: batchAddFavorites()")
    print(f"  5. Wait ~{est_minutes:.0f} min until alert pops up")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate Amap batch-add JS script from GCJ-02 JSON."
    )
    parser.add_argument(
        "--input", "-i",
        default="baidu_favorites_gcj02.json",
        help="Input JSON from convert_coords.py (default: baidu_favorites_gcj02.json)",
    )
    parser.add_argument(
        "--output", "-o",
        default="amap_batch_add.js",
        help="Output JavaScript file (default: amap_batch_add.js)",
    )
    parser.add_argument(
        "--delay", "-d",
        type=float,
        default=2.5,
        help="Delay in seconds between requests (default: 2.5, increase if rate-limited)",
    )
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"[ERROR] Input file not found: {args.input}")
        print("        Run convert_coords.py first to generate it.")
        sys.exit(1)

    generate_js(args.input, args.output, delay=args.delay)
